### ISSUE TITLE
Add Badlion to test client

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#18]
BadLion managed to bypass the Test Client.

**Comment by LoneDev6** [comment]
Same answer as this: https://github.com/LoneDev6/Issues-Wraith/issues/17#issuecomment-725582625

Anyway, which Badlion version are you using? Can you send it here? Thanks

**Comment by Ofek270704** [comment]
1.16.3

**Comment by CloudeLecaw** [comment]
this can be done allready
you can add as many clients as u want as long wratih can dedtect them

Note if the developer of a client does not give a handshake for authentication all anticheats will think its a vanilla clients. 

```
  kick-mods:
    chatcraft: true
    fabric: true
    forge: true
    rift: true
    labymod: true
    liteloader: true
    5zig: true
    forgewurst: true
    Skill: true
    Parrot: true
    PoisonHQ: true
    Jigsaw: true
    hyperium: true
    LOLIMAHACKER: true
    PxMod: true
    Winterware: true
    PixelClient: true
    Impact: true
    EMC: true
    Subsystem: true
    Lunar-Client: true
    schematica: true
    worlddownloader: true
    worldedit: true
    advancedcapes: true
    jei: true
    nei: true
    quickhotbar: true
    xaerominimap: true
    XaeroMinimap: true
    journeymap_channel: true
    journeymap: true
    InventoryTweaks: true
    BSprint: true
    xray: true
    x-ray: true
    X-Ray: true
    waila: true
    hwyla: true
    BetterCraft: true
    Huzuni: true
    Flare: true
    Metro: true
    Nodus: true
    SkillClient: true
    Wolfram: true
    Iridium: true
    United: true
    Solstice: true
    GarPloit: true
    Saint: true
    Dezztroyz: true
    LiquidBounce: true
    Wurst: true
    LunarClient: true
    Lunar_Client: true
    lunarclient: true
    lunarclient:cc5174d: true
    lunarclient:f002592: true
    lunarclient:^: true
```

here is our current list if u want, might it help u^^
