### ISSUE TITLE
[BUG] ItemsAdder false positive blocks

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/Issues-Wraith#27]
**Describe the bug**
Seems new itemsadder blocks (based on non placeable material like PAPER) trigger the scraffolding hack detection sometimes.

Probably a fix would be to check if CPS is low? or if it's an ItemsAdder block + getType().isBlock() == false

**Comment by LoneDev6** [comment]
Happens also when using fire igniters:

```yml
  blue_fire_chemical_igniter:
    enabled: true
    display_name: Blue Fire Chemical Igniter
    lore:
      - "&6[ &eChemical Materials&6]"
      - ""
      - "&7Contains:"
      - "&8- &7Copper(I) chloride"
      - "&8- &7butane"
      - ""
      - "&7(rightclick on fire to use)"
    resource:
      generate: true
      material: IRON_SWORD
      textures:
      - "item/blue_fire_chemical_igniter"
    durability:
      max_custom_durability: 8
    attribute_modifiers:
      mainhand:
        attackDamage: 0.0
        attackSpeed: 4.0
    item_flags:
    - HIDE_ATTRIBUTES
    events:
      interact:
        right:
          cancel: true
          replace_block:
            from: FIRE
            to: blue_fire
            decrement_durability: 1
          play_sound:
            name: minecraft:block.fire.extinguish
            volume: 1
            pitch: 1.2
```
