### ISSUE TITLE
2.1.2 does not block brands...

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#35]
We noticed in testing that brands does not get blocked in 2.1.2
We are using Paper 1.16.5 Build 721
Java 11.0.10+9
Wraith 2.1.2
i tested it just with forge and farbric with a player profil (no op no admin permission)

in both cases i was able to join in 2.1.2
Wraith itself sees the brand but does not react...
![image](https://user-images.githubusercontent.com/12080017/119606292-9d13fc00-bdf2-11eb-9503-c19d0c9fd013.png)

with wraith 2.1.1 the brands where blocked fine.
So for now we went back to 2.1.1

here is our clients-config of 2.1.2 - it might helps.
```
anti-hacks:
  enabled: true
  ban:
    enabled: false
    after-join-attempts: 5
  testclient:
    duration-seconds: 35
    freeze-player: false
    deny-commands-player: true
    auto-onjoin:
      enabled: false
      disable-aristois: false
    ban:
      enabled: false
      after-fails: 5
    teleport-after-success:
      enabled: false
      world: world
      x: 33
      y: 64
      z: 335
  kick-mods:
    chatcraft: true
    5zig: true
    forgewurst: true
    schematica: true
    worlddownloader: true
    worldedit: true
    advancedcapes: true
    quickhotbar: true
    xaerominimap: true
    XaeroMinimap: true
    journeymap_channel: true
    journeymap: true
    InventoryTweaks: true
    BSprint: true
    xray: true
    x-ray: true
    X-Ray: true
    waila: true
    hwyla: true
    NEI: true
    jei: true
  block-lunarclient:
    block-staff-modules: true
    blocked-modules:
      replaymod: true
      one_seven_visuals: true
      fps: true
      cps: true
      skyblockAddons: true
      toggleSneak: true
      zoom: true
      hypixel_mod: true
      armorstatus: true
      keystrokes: true
      coords: true
      daycounter: true
      crosshair: true
      potioneffects: true
      directionhud: true
      waypoints: true
      scoreboard: true
      potion_counter: true
      ping: true
      motionBlur: true
      chat: true
      scrollable_tooltips: true
      uhc_overlay: true
      particleMultiplierMod: true
      nickHider: true
      cooldowns: true
      worldedit_cui: true
      clock: true
      stopwatch: true
      memory: true
      combo: true
      range: true
      time_changer: true
      serverAddressMod: true
      saturation: true
      itemPhysic: true
      itemTrackerChild: true
      shinyPots: true
      block_outline: true
      screenshot: true
      fov_mod: true
      textHotKey: true
      netgraph: true
      mumble-link: true
      items2d: true
      bossbar: true
      freelook: true
      teamview: true
      resource_display: true
      menu_blur: true
      hitbox: true
  block-badlion:
    mods:
      Animations:
        blocked: true
      ArmorStatus:
        blocked: true
      AutoFriend:
        blocked: true
      AutoGG:
        blocked: true
      AutoText:
        blocked: true
      AutoTip:
        blocked: true
      Block Overlay:
        blocked: true
      BlockInfo:
        blocked: true
      BossBar:
        blocked: true
      Chat:
        blocked: true
      Chunk Borders:
        blocked: true
      Clear Glass:
        blocked: true
      ClearWater:
        blocked: true
      Clock:
        blocked: true
      Combo Counter:
        blocked: true
      Coordinates:
        blocked: true
      CPS:
        blocked: true
      Crosshair:
        blocked: true
      Custom Fonts:
        blocked: true
      Direction:
        blocked: true
      EnchantGlint:
        blocked: true
      FOV Changer:
        blocked: true
      FPS:
        blocked: true
      Fullbright:
        blocked: true
      Hit Color:
        blocked: true
      Hitboxes:
        blocked: true
      InventoryBlur:
        blocked: true
      Item Counter:
        blocked: true
      Item Info:
        blocked: true
      Item Physics:
        blocked: true
      Item Tracker:
        blocked: true
      JustEnoughItems:
        blocked: true
      Keystrokes:
        blocked: true
      LevelHead:
        blocked: true
      Light Overlay:
        blocked: true
      Memory:
        blocked: true
      MiniMap:
        blocked: true
      MLG Cobweb:
        blocked: true
      MotionBlur:
        blocked: true
      MumbleLink:
        blocked: true
      Music:
        blocked: true
      Name History:
        blocked: true
      NickHider:
        blocked: true
      NotEnoughUpdates:
        blocked: true
      Notifications:
        blocked: true
      Pack Display:
        blocked: true
      Pack Tweaks:
        blocked: true
      Particles:
        blocked: true
      Perspective:
        blocked: true
      Ping:
        blocked: true
      Player Counter:
        blocked: true
      PotionStatus:
        blocked: true
      Protection:
        blocked: true
      Quickplay:
        blocked: true
      Reach Display:
        blocked: true
      Replay:
        blocked: true
      Saturation:
        blocked: true
      Schematica:
        blocked: true
      Scoreboard:
        blocked: true
      Server Address:
        blocked: true
      Shinypots:
        blocked: true
      SkyblockAddons:
        blocked: true
      Stopwatch:
        blocked: true
      TcpNoDelay:
        blocked: true
      TeamSpeak:
        blocked: true
      TimeChanger:
        blocked: true
      Timers:
        blocked: true
      ToggleChat:
        blocked: true
      ToggleSneak:
        blocked: true
      ToggleSprint:
        blocked: true
      Waypoints:
        blocked: true
      WeatherChanger:
        blocked: true
      World Edit CUI:
        blocked: true
      Zoom:
        blocked: true
      Clan Wars:
        blocked: true
      ColorSaturation:
        blocked: true
  block-5zig:
    mods:
      PotionEffects: true
      PotionIndicator: true
      Armor: true
      Saturation: true
      EntityHealth: true
      AutoReconnect: true
  block-channels:
    block-empty-channel: true
    channels:
      WDL|INIT:
        blocked: true
        description: WorldDownloader
      WDL|CONTROL:
        blocked: true
        description: WorldDownloader
      WDL|REQUEST:
        blocked: true
        description: WorldDownloader
      wdl:init:
        blocked: true
        description: WorldDownloader
      wdl:control:
        blocked: true
        description: WorldDownloader
      wdl:request:
        blocked: true
        description: WorldDownloader
      WECUI:
        blocked: true
        description: World Edit CUI
      schematica:
        blocked: true
        description: Schematica
      journeymap_channel:
        blocked: true
        description: Journeymap
      l:world_info:
        blocked: true
        description: Journeymap
      BSprint:
        blocked: true
        description: BSprint
      l:bsprint:
        blocked: true
        description: BSprint
      l:bsm:
        blocked: true
        description: BSprint
      JEI:
        blocked: true
        description: JEI
      XaeroMinimap:
        blocked: true
        description: XaeroMinimap
      InventoryTweaks:
        blocked: true
        description: InventoryTweaks
      waila:
        blocked: true
        description: waila
      CPS_BAN_THIS_NIGGER:
        blocked: true
        description: VapeCracked
      L0LIMAHCKER:
        blocked: true
        description: VapeCracked
      LOLIMAHCKER:
        blocked: true
        description: VapeCracked
      EROUAXWASHERE:
        blocked: true
        description: VapeCracked
      EARWAXWASHERE:
        blocked: true
        description: VapeCracked
      '#unbanearwax':
        blocked: true
        description: VapeCracked
      194620356vv0:
        blocked: true
        description: VapeCracked
      'Created By ':
        blocked: true
        description: VapeCracked
      MC|Pixel:
        blocked: true
        description: Pixel Client
      LC|Brand:
        blocked: true
        description: Winterware
      LiteLoader:
        blocked: true
        description: LiteLoader
      liteloader:
        blocked: true
        description: LiteLoader
      CB|INIT:
        blocked: true
        description: CheatBreaker
      CB-Binary:
        blocked: true
        description: CheatBreaker
      LABYMOD:
        blocked: true
        description: Labymod
      LMC:
        blocked: true
        description: Labymodv3
      PX|Version:
        blocked: true
        description: PX Mod
      hyperium:
        blocked: true
        description: hyperium
      EMC:
        blocked: true
        description: EMC
      customGuiOpenBspkrs:
        blocked: true
        description: BspkrsCore
      mincraftpvphcker:
        blocked: true
        description: BspkrsCore
      0SO1Lk2KASxzsd:
        blocked: true
        description: BspkrsCore
      cock:
        blocked: true
        description: Merge
      gg:
        blocked: true
        description: Reach Mod
      lmaohax:
        blocked: true
        description: Incognito
      n:
        blocked: true
        description: 'TimeChanger '
      reach:
        blocked: true
        description: Reach Mod
      MCnetHandler:
        blocked: true
        description: 'TimeChanger '
      0SSxzsd:
        blocked: true
        description: Hacked Client
      Parrot:
        blocked: true
        description: Parrot
      Skill:
        blocked: true
        description: Skill
      Aristois:
        blocked: true
        description: Aristois
      PoisonHQ:
        blocked: true
        description: PoisonHQ
      Impact:
        blocked: true
        description: Impact
      Synergy:
        blocked: true
        description: Synergy
      AC-Client:
        blocked: true
        description: Aero Client
      OCMC:
        blocked: true
        description: OCMC
      CRYSTAL|6LAKS0TRIES:
        blocked: true
        description: CRYSTAL
      CRYSTAL|KZ1LM9TO:
        blocked: true
        description: CRYSTAL
      BLC|M:
        blocked: true
        description: Remix
  block-brands:
    brands:
      fabric: true
      forge: true
      LunarClient: true
      Lunar_Client: true
      lunarclient^: true
      rift: true
      WorldDownloader: true
      LiquidBounce: true
      Lunar-Client: true
      PixelClient: true
      Subsystem: true
      hyperium: true
      Vanilla: true
      !!binary "ADA3VmFuaWxsYQ==": true
      BLC|M: true
      BLC|KOZ9FP: true
      Dezztroyz: true
      GarPloit: true
      United: true
      Wolfram: true
      BetterCraft: true
      Huzuni: true
      Flare: true
      Metro: true
      Nodus: true
      SkillClient: true
      Iridium: true
      Solstice: true
      Saint: true
      Wurst: true
      Winterware: true
      PxMod: true
      Jigsaw: true
      PLC18: true
anti-dupe:
  0tick-farm:
    enabled: true
    delete-machine: true
    notify-op: true
  carpet-rail:
    enabled: true
    delete-machine: true
    notify-op: true
hide-plugins:
  enabled: false
  hide-every-tab-suggestion: false
  settings:
    chestcommands:
      fix-tab-commands:
        enabled: true
        commands:
        - example2
        - example1
        - example
    whitelist:
      enabled: false
      commands:
      - tpa
      - ia^
      - /^
      - pet^
      - me^
      - sethome
      - home
      - trade
      - 'itemsadder:'
      - itemsadder
      - aach
      - abandonallclaims
      - abgetmoney
      - afk
      - atm
      - back
      - backpack
      - bal
      - balance
      - bank
      - chatreplay
      - claim
      - claimexplosion
      - claimexplosions
      - containertrust
      - accesstrust
      - permissiontrust
      - givepet
      - griefprevention
      - claimlist
      - delhome
      - ebp^
      - emoji
      - e^
      - hat
      - home^
      - homes
      - hpc
      - nick
      - emote
      - ia
      - m^
      - mail
      - market
      - 'market:'
      - marketcreate
      - marketdelete
      - marketclose
      - marketdescription
      - marketlist
      - marketopen
      - marketmove
      - mclaim
      - menu
      - money
      - msg^
      - mt^
      - pet
      - petbeacon
      - petcall
      - petchooseskilltree
      - petinfo
      - petinventory
      - petshop
      - petskill
      - petstore
      - petswitch
      - players
      - pp
      - profilo
      - pvp
      - qs
      - quests
      - r^
      - rank
      - rankconfirm
      - ranks
      - remhome
      - rtp
      - sethome
      - shop^
      - sit
      - spawn
      - t^
      - tell
      - tpa
      - tpaaccept
      - tpacancel
      - tpaccept
      - tpahere
      - tpask
      - tpdeny
      - tpyes
      - trade
      - trust
      - unclaim
      - w
      - warp
      - warps
      - wild
    blacklist:
      enabled: true
      commands:
      - gmc
      - gamemode
      - op^
      - deop
      - '?'
      - 'bukkit:'
      - pl^
      - plugins
      - about^
      - icanhasbukkit
      - help
      - version
      - ver
      - plugman
      - multiverse
      - mv
      - iagive
      - iaget
      - iareload
      - iadur
      - iarepair
      - reload
      - stop
      - save-all
      - ban
      - tempban
      - worldguard
      - 'worldguard:'
      - minecraft:teammsg
      - minecraft:tm
      - minecraft:me
      - minecraft:list
      - minecraft:help
      - minecraft:trigger
      - minecraft:w
      - worldedit
      - 'worldedit:'
      - 'exploitfixer:'
      - exploitfixer^
```
