### ISSUE TITLE
[BUG] Speed false positive

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/Issues-Wraith#41]
**Describe the bug**
Seems speed detection is a bit bugged since last updates

**To Reproduce**
1. Walk around, try to run normally
2. See that wraith prints "increment speed" log (if debug is enabled) multiple times despite the fact the player is not running very fast

**Expected behavior**
No detection in this case

**Screenshots**
![immagine](https://user-images.githubusercontent.com/27242001/121030926-35728f00-c7aa-11eb-80cb-5db661655106.png)

**Info (please complete the following information):**
 - Server version: This server is running Paper version git-Paper-733 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Client version: 1.16.5
 - Plugin version: 2.1.3

**Comment by LoneDev6** [comment]
A note from a user:
> No my players only use Elytras and some time have the speed effect from beacons. And I run the Spigot Plugin on a Fork from Spigot named PURPUR Mc.
Thanks I change that!

**Comment by CloudeLecaw** [comment]
be sure you tested this with Version 2.1.3?
Just asking because it sounds more logic to me to use the 2.2.2 or maybe a 2.2.3 that you currently develop...

**Comment by LoneDev6** [comment]
> 
> 
> be sure you tested this with Version 2.1.3?
> Just asking because it sounds more logic to me to use the 2.2.2 or maybe a 2.2.3 that you currently develop...

Yes it's the indev version

**Comment by LoneDev6** [comment]
Changed:
```yml
    speed:
      enabled: true
      vl: 5
      ms: 2000
      max-speed: 15
      action-name: "Kicked"
      command: kick {player} {w-prefix} &cYou cannot use speedhack on this server.
      notification:
        op: true
        permission: true
        console: true
        ```

also updated some stuff in the plugin code.
