### ISSUE TITLE
[Suggestion] Optional No Meassage for PacketLimiter

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#64]
Currently on Startup of Wraith Wraith suggest to use PacketLimiter Plugin.

Well PaperMC isself has this option: (paper.yml)
```
  packet-limiter:
    kick-message: '&cSent too many packets'
    limits:
      all:
        interval: 7.0
        max-packet-rate: 500.0
      PacketPlayInAutoRecipe:
        interval: 4.0
        max-packet-rate: 5.0
        action: DROP
```

So my question is - does it make sense to use this PacketLimiter?
And the next question would be.. If No - Would it make sense to add an Option that when seen that PaperMC is used not giving the Suggestion to install PacketLimiter? 
Even if your using it Wraith still suggest it on startup

Waithing for your Responce :-)
