### ISSUE TITLE
Wraith kick vanilla planer with vanilla launcher for forge

### ISSUE THREAD

**Issue by iSeitan** [LoneDev6/Issues-Wraith#67]
Connecting with vanilla launcher with no mods

**Expected behavior**
If   advanced:
    send-forge-packets: false
    send-fabric-packets: false
    and a player connect vanilla they should not get kicked
    
    BUT player with forge/fabric/cheat client gets kicked

**Info (please complete the following information):**
 - Server version: paper paper-1.18.2-312
 - Client version: vanilla 1.18.2
 - Plugin version: 2.3.0

Please tell me how to fix this issue, its either let forge mods/fabric mods connect and vanilla player connect OR nobody connects..

**Comment by iSeitan** [comment]
I have to stop using this plugin wich i bought, can i get a refund or get this bug fixed please

**Comment by thefourcraft** [comment]
you need to allow forge players to join the server... this is public information that is available on the plugin wiki...
```yml
block-clients:
    forge:
      enabled-check: true
      description: "Forge"
      brands:
        enabled-check: true
        list:
          forge: true
          fml: true
      channels:
        enabled-check: true
        list:
          FORGE: true
          l:forge: true
          FML: true
          l:fml: true
          "FML|HS": true
          "fml:hs": true
          "fml:loginwrapper": true
          "fml:handshake": true
          "fml:play": true
      forge-mods:     
        enabled-check: true
        list: #             <-------------------- HERE
          5zig: true
          forgewurst: true
          schematica: true
          worlddownloader: true
          # ....
```
You can find all the info here:
https://wraith.devs.beer/
