### ISSUE TITLE
[BUG] fly in the water ?

### ISSUE THREAD

**Issue by BartosB13** [LoneDev6/Issues-Wraith#84]
**Describe the bug**
It seems like my players are swimming in water (ice mining etc) the plugin detects fake fly alerts. Screen below. It is worth adding that the players had shoes from Depth Strider 3.
My settings for flying:

```
  flight:
    enabled: true
    disable-if-has-elytra-equipped: true
    violations:
      disable-check-if-good-greather-than: 150
      start:
        everyone:
          good: 50
          bad: 0
        playtime-bonus:
          each-hour: 2
          good: 2
          bad: 0
      detection:
        min-violations:
          good: 20
          bad: 40
      reset-threshold:
        after-seconds: 100
      edit:
        good: 3
        bad: 3
```

**Screenshots**
![W bug fly water](https://user-images.githubusercontent.com/89303317/183251058-1d3af2f5-51d6-48cc-841a-22a2ee2bdd3d.png)

**Info (please complete the following information):**
 - Server version: Paper 1.19.0
 - Client version: 1.19.0
 - Plugin version: 2.3.3
