### ISSUE TITLE
[BUG] scaffoldwalk + swift sneak 3 = bug?

### ISSUE THREAD

**Issue by BartosB13** [LoneDev6/Issues-Wraith#85]
**Describe the bug**
I am writing this for information only. I had a strange case on the server. It is very likely that the new enchant swift sneak 3 may cause false scaffoldwalk detections.

My settings for this event. The player was rebuilding the fortress in nether with the swift sneak 3 enchant.
```
    scaffoldwalk:
      enabled: true
      vl: 15
      seconds: 3
```

**Info (please complete the following information):**
 - Server version: Paper 1.19.0
 - Client version: MC 1.19.0 +Optifine
 - Plugin version: 2.3.3
